# Version of docker-compose syntax, locking in the version to ensure new version releases won't break this configuration
version: "3.9"

# Main block: typically comprise of one or more services for the app
services:
  # Name of service
  app:
    # Setting Build docker context to current directory
    build:
      context: .
      # Overriding development mode to true for this file (docker-compose.yml), only used during development 
      args:
        - DEV=true
    # Maps port 8000 on local machine to port 8000 in docker container (to access netowork when we want to connect to the server)
    ports:
      - "8000:8000"
    # Mapping directories from our system to the docker container
    # Syncs code in project to code in container, don't have to rebuild container everytime we update code
    volumes:
      - ./app:/app
    # Command used to run service, this is the default command that can be overriden
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # Tell our app how to connect to the database
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    # Wait for db service to start before starting app service
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    # Set initial db configuration for new db service
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
